# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Transparency Toolkit Styleguide
email: info@transparencytoolkit.org
description: > # This is a styleguide for Transparency Toolkit
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://transparencytoolkit.org" # the base hostname & protocol for your site
twitter_username: transparencykit
github_username:  transparencytoolkit

# Build settings
markdown: kramdown
